# cmd_exp.awk
#
# Command ID Export 
#
# Inputs : Visual Studio resource ID header file
# Outputs : C source file
#
# This build step generates a table mapping all the Visual
# Studio resource ID's for commands into Scheme keyword names.
# Any resource ID beginning with "CMD_" gets a mapping table
# entry.
#

BEGIN {
  print "/* Generated by cmd_exp.awk, DO NOT MODIFY!!! */";
  print "";
  print "struct {";
  print "   UINT _resID;";
  print "   char *_keyword;";
  print "} commandIDTable[] = {";
}

/CMD_/ { 
  string_define = $2;

  string_keyword = tolower($2);

  sub("cmd", "cmd", string_keyword);

  while (sub("_", "-", string_keyword))
    ;

  print "   { " string_define ", \"" string_keyword "\" },";
}

END {
  print "   {0, NULL}, "
  print "};";
}