(use-package! "unit-test")

(define-test let*
  (let ((side-effect-0 #f)
	(side-effect-1 #f)
	(side-effect-2 #f))
    (let* ((x 0)
	  (y 1)
	  (z 2))
      (set! side-effect-0 #t)
      (check (= x 0))
      (check (= y 1))
      (check (= z 2))
      (set! side-effect-1 #t)
      (set! x 10)
      (incr! y)
      (check (= x 10))
      (check (= y 2))
      (check (= z 2))
      (set! side-effect-2 #t))
    (check side-effect-0)
    (check side-effect-1)
    (check side-effect-2))

  (let ((x 10) 
	(y 20))
    (let* ((x 100)
	   (y x))
      (check (= x 100))
      (check (= y 100)))))

