(use-package! "unit-test")


(define (make-all-byte-combo-string)
  (let ((p (open-output-string)))
    (set-port-translate-mode! p #f)
    (dotimes (ii 256)
      (dotimes (jj 256)
        (display (integer->char ii) p)
        (display (integer->char jj) p)))
    (get-output-string p)))

(define-test string-round-trip
  (dotimes (n 256)
    (test-case (can-read/write-round-trip? (make-string 1 (integer->char n)))))
  (dotimes (n 256)
    (test-case (can-read/write-round-trip? (make-string 3 (integer->char n)))))
  (let ((abc-str (make-all-byte-combo-string)))
    (test-case (can-read/write-round-trip? "\t\n"))
    (test-case (can-read/write-round-trip? " \n hello\n\t"))
    (test-case (can-read/write-round-trip? "\"\"\""))
    (test-case (can-read/write-round-trip? "01234567890abcdefghihjkilmnopqrstuvwxyz"))
    (test-case (can-read/write-round-trip? abc-str))
    (test-case (= (length abc-str) (* 256 256 2)))))


(define-test string-escapes
  (test-case (= 0  (char->integer (string-ref "\000" 0))))
  (test-case (= 1  (char->integer (string-ref "\1" 0))))
  (test-case (= 2  (char->integer (string-ref "\2" 0))))
  (test-case (= 3  (char->integer (string-ref "\3" 0))))
  (test-case (= 4  (char->integer (string-ref "\4" 0))))
  (test-case (= 5  (char->integer (string-ref "\5" 0))))
  (test-case (= 6  (char->integer (string-ref "\6" 0))))
  (test-case (= 7  (char->integer (string-ref "\7" 0))))
  (test-case (= 8  (char->integer (string-ref "\10" 0))))
  (test-case (= 9  (char->integer (string-ref "\11" 0))))
  (test-case (= 10 (char->integer (string-ref "\12" 0))))
  (test-case (= 11 (char->integer (string-ref "\13" 0))))
  (test-case (= 12 (char->integer (string-ref "\14" 0))))
  (test-case (= 13 (char->integer (string-ref "\15" 0))))
  (test-case (= 14 (char->integer (string-ref "\16" 0))))
  (test-case (= 15 (char->integer (string-ref "\17" 0))))
  (test-case (= 16 (char->integer (string-ref "\20" 0))))
  (test-case (= 17 (char->integer (string-ref "\21" 0))))
  (test-case (= 18 (char->integer (string-ref "\22" 0))))
  (test-case (= 19 (char->integer (string-ref "\23" 0))))

  (test-case (= 1  (char->integer (string-ref "\19" 0))))
  (test-case (= #\9 (string-ref "\19" 1)))

  (test-case (equal? (write-to-string (make-string 1 (integer->char 0  ))) "\"\\000\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 1  ))) "\"\\001\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 2  ))) "\"\\002\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 3  ))) "\"\\003\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 4  ))) "\"\\004\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 5  ))) "\"\\005\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 6  ))) "\"\\006\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 7  ))) "\"\\007\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 8  ))) "\"\\010\""))

  (test-case (equal? (write-to-string (make-string 1 #\\               ))  "\"\\\\\""))
  (test-case (equal? (write-to-string (make-string 1 #\"               ))  "\"\\\"\""))
  (test-case (equal? (write-to-string (make-string 1 #\newline         ))  "\"\\n\"" ))
  (test-case (equal? (write-to-string (make-string 1 #\cr              ))  "\"\\r\"" ))
  (test-case (equal? (write-to-string (make-string 1 #\tab             ))  "\"\\t\"" ))

  (test-case (equal? (write-to-string (make-string 1 (integer->char 128))) "\"\\200\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 129))) "\"\\201\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 130))) "\"\\202\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 131))) "\"\\203\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 132))) "\"\\204\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 133))) "\"\\205\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 134))) "\"\\206\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 135))) "\"\\207\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 136))) "\"\\210\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 137))) "\"\\211\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 138))) "\"\\212\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 139))) "\"\\213\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 140))) "\"\\214\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 141))) "\"\\215\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 142))) "\"\\216\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 143))) "\"\\217\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 144))) "\"\\220\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 145))) "\"\\221\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 146))) "\"\\222\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 147))) "\"\\223\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 148))) "\"\\224\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 149))) "\"\\225\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 150))) "\"\\226\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 151))) "\"\\227\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 152))) "\"\\230\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 153))) "\"\\231\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 154))) "\"\\232\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 155))) "\"\\233\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 156))) "\"\\234\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 157))) "\"\\235\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 158))) "\"\\236\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 159))) "\"\\237\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 160))) "\"\\240\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 161))) "\"\\241\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 162))) "\"\\242\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 163))) "\"\\243\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 164))) "\"\\244\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 165))) "\"\\245\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 166))) "\"\\246\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 167))) "\"\\247\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 168))) "\"\\250\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 169))) "\"\\251\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 170))) "\"\\252\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 171))) "\"\\253\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 172))) "\"\\254\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 173))) "\"\\255\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 174))) "\"\\256\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 175))) "\"\\257\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 176))) "\"\\260\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 177))) "\"\\261\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 178))) "\"\\262\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 179))) "\"\\263\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 180))) "\"\\264\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 181))) "\"\\265\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 182))) "\"\\266\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 183))) "\"\\267\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 184))) "\"\\270\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 185))) "\"\\271\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 186))) "\"\\272\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 187))) "\"\\273\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 188))) "\"\\274\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 189))) "\"\\275\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 190))) "\"\\276\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 191))) "\"\\277\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 192))) "\"\\300\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 193))) "\"\\301\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 194))) "\"\\302\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 195))) "\"\\303\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 196))) "\"\\304\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 197))) "\"\\305\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 198))) "\"\\306\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 199))) "\"\\307\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 200))) "\"\\310\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 201))) "\"\\311\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 202))) "\"\\312\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 203))) "\"\\313\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 204))) "\"\\314\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 205))) "\"\\315\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 206))) "\"\\316\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 207))) "\"\\317\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 208))) "\"\\320\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 209))) "\"\\321\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 210))) "\"\\322\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 211))) "\"\\323\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 212))) "\"\\324\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 213))) "\"\\325\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 214))) "\"\\326\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 215))) "\"\\327\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 216))) "\"\\330\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 217))) "\"\\331\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 218))) "\"\\332\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 219))) "\"\\333\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 220))) "\"\\334\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 221))) "\"\\335\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 222))) "\"\\336\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 223))) "\"\\337\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 224))) "\"\\340\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 225))) "\"\\341\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 226))) "\"\\342\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 227))) "\"\\343\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 228))) "\"\\344\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 229))) "\"\\345\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 230))) "\"\\346\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 231))) "\"\\347\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 232))) "\"\\350\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 233))) "\"\\351\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 234))) "\"\\352\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 235))) "\"\\353\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 236))) "\"\\354\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 237))) "\"\\355\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 238))) "\"\\356\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 239))) "\"\\357\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 240))) "\"\\360\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 241))) "\"\\361\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 242))) "\"\\362\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 243))) "\"\\363\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 244))) "\"\\364\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 245))) "\"\\365\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 246))) "\"\\366\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 247))) "\"\\367\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 248))) "\"\\370\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 249))) "\"\\371\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 250))) "\"\\372\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 251))) "\"\\373\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 252))) "\"\\374\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 253))) "\"\\375\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 254))) "\"\\376\""))
  (test-case (equal? (write-to-string (make-string 1 (integer->char 255))) "\"\\377\""))
  )

