(use-package! "unit-test")

(define-test path-string->list
  (test-case (runtime-error? (path-string->list 12)))
  (test-case (runtime-error? (path-string->list :symbol)))
  (test-case (runtime-error? (path-string->list #t)))
  (test-case (equal? (path-string->list "") '()))
  (test-case (equal? (path-string->list ".") '(".")))
  (test-case (equal? (path-string->list "..") '("..")))
  (test-case (equal? (path-string->list "..:.") '(".." ".")))
  (test-case (equal? (path-string->list "..;.") '(".." ".")))
  (test-case (equal? (path-string->list ".:..") '("." "..")))
  (test-case (equal? (path-string->list ".;..") '("." "..")))
  (platform-case
   ((:linux)
    ;; Quoting doesn't work on *nix platforms
    (test-case (equal? (path-string->list ".\\:..") '(".:..")))
    (test-case (equal? (path-string->list ".\\;..") '(".;.."))))
   ((:win32)
    #t))
  (test-case (equal? (path-string->list "1;2;3;4") '("1" "2" "3" "4")))
  (test-case (equal? (path-string->list "1;.;..;4") '("1" "." ".." "4")))
  (test-case (equal? (path-string->list "./;..;~;/usr/lib/windmill") '("./" ".." "~" "/usr/lib/windmill")))
  (test-case (equal? (path-string->list "./;..;~;/usr/lib/windmill") '("./" ".." "~" "/usr/lib/windmill")))
  (test-case (equal? (path-string->list ";2;3;4") '("2" "3" "4")))
  (test-case (equal? (path-string->list "1;2;;4") '("1" "2" "4")))
  (test-case (equal? (path-string->list "1;2;3;") '("1" "2" "3")))
  (test-case (equal? (path-string->list "1;;;4") '("1" "4")))  
  )