(use-package! "unit-test")

(define-test fast-io-atoms
  (check (can-fast-io-round-trip? '()))
  (check (can-fast-io-round-trip? #t))
  (check (can-fast-io-round-trip? #f))
  (check (can-fast-io-round-trip? :keyword))
  (check (can-fast-io-round-trip? 'symbol))
  (check (can-fast-io-round-trip? #\nul))
  (check (can-fast-io-round-trip? #\a))
  (check (can-fast-io-round-trip? ""))
  (check (can-fast-io-round-trip? "string"))
  (check (can-fast-io-round-trip? (system-info :most-negative-fixnum)))
  (check (can-fast-io-round-trip? -3000000000000))
  (check (can-fast-io-round-trip? -1000000000000))
  (check (can-fast-io-round-trip? -4294967296))
  (check (can-fast-io-round-trip? -4294967295))
  (check (can-fast-io-round-trip? -3000000000))
  (check (can-fast-io-round-trip? -2147483648))
  (check (can-fast-io-round-trip? -2147483647))
  (check (can-fast-io-round-trip? -1000000000))
  (check (can-fast-io-round-trip? -65536))
  (check (can-fast-io-round-trip? -65535))
  (check (can-fast-io-round-trip? -32768))
  (check (can-fast-io-round-trip? -32767))
  (check (can-fast-io-round-trip? -10000))
  (check (can-fast-io-round-trip? -128))
  (check (can-fast-io-round-trip? -127))
  (check (can-fast-io-round-trip? -1))
  (check (can-fast-io-round-trip? 0))
  (check (can-fast-io-round-trip? 1))
  (check (can-fast-io-round-trip? 127))  
  (check (can-fast-io-round-trip? 128))
  (check (can-fast-io-round-trip? 10000))
  (check (can-fast-io-round-trip? 32767))
  (check (can-fast-io-round-trip? 32768))
  (check (can-fast-io-round-trip? 65535))
  (check (can-fast-io-round-trip? 65536))
  (check (can-fast-io-round-trip? 1000000000))
  (check (can-fast-io-round-trip? 2147483647))
  (check (can-fast-io-round-trip? 2147483648))
  (check (can-fast-io-round-trip? 3000000000))
  (check (can-fast-io-round-trip? 4294967295))
  (check (can-fast-io-round-trip? 4294967296))
  (check (can-fast-io-round-trip? 1000000000000))
  (check (can-fast-io-round-trip? 3000000000000))
  (check (can-fast-io-round-trip? (system-info :most-positive-fixnum)))
  (check (can-fast-io-round-trip? -1.0))
  (check (can-fast-io-round-trip? 0.0))
  (check (can-fast-io-round-trip? 1.0))
  (check (can-fast-io-round-trip? #inan))
  (check (can-fast-io-round-trip? #iposinf))
  (check (can-fast-io-round-trip? #ineginf))
  (check (can-fast-io-round-trip? (system-info :most-negative-flonum)))
  (check (can-fast-io-round-trip? (system-info :most-positive-flonum)))
  (check (can-fast-io-round-trip? (system-info :flonum-epsilon)))
  (check (can-fast-io-round-trip? (- (system-info :flonum-epsilon))))
  (check (can-fast-io-round-trip? -1-2i))
  (check (can-fast-io-round-trip? 1+2i))
  (check (can-fast-io-round-trip? 0+0i)))
