(use-package! "unit-test")

(define-test is-directory-filename?
  (check (is-directory-filename? ""))
  (check (is-directory-filename? "foo/"))
  (check (is-directory-filename? "/"))
  (check (is-directory-filename? "."))
  (check (is-directory-filename? ".."))
  (check (is-directory-filename? "./"))
  (check (is-directory-filename? "../"))

  (check (is-directory-filename? "/foo/"))

  (check (is-directory-filename? "./../"))
  (check (is-directory-filename? "./../"))
  (check (is-directory-filename? "./foo/"))
  (check (is-directory-filename? "./../foo/"))
  (check (not (is-directory-filename? "./../foo")))
  (check (not (is-directory-filename? "./../*")))
  (check (not (is-directory-filename? "./../*.*")))
  (check (is-directory-filename? "./../**/"))
  (check (not (is-directory-filename? "./../**")))

  (check (is-directory-filename? "../"))
  (check (is-directory-filename? "../"))
  (check (is-directory-filename? "foo/"))
  (check (is-directory-filename? "../foo/"))
  (check (not (is-directory-filename? "../foo")))
  (check (not (is-directory-filename? "../*")))
  (check (not (is-directory-filename? "../*.*")))
  (check (is-directory-filename? "../**/"))
  (check (not (is-directory-filename? "../**"))))
