(use-package! "unit-test")

(define-test number-type-predicates
  (check (integer? 0))
  (check (integer? 1))
  (check (integer? 100))
  (check (rational? 0))
  (check (rational? 1))
  (check (rational? 100))
  (check (real? 0))
  (check (real? 1))
  (check (real? 100))
  (check (not (complex? 0)))
  (check (not (complex? 1)))
  (check (not (complex? 100)))
  (check (number? 0))
  (check (number? 1))
  (check (number? 100))
  (check (not (integer? 0.0)))
  (check (not (integer? 1.0)))
  (check (not (integer? 100.0)))
  (check (not (rational? 0.0)))
  (check (not (rational? 1.0)))
  (check (not (rational? 100.0)))
  (check (real? 0.0))
  (check (real? 1.0))
  (check (real? 100.0))
  (check (not (complex? :not-complex)))
  (check (not (complex? 0.0)))
  (check (not (complex? 1.0)))
  (check (not (complex? 100.0)))
  (check (not (number? :foo)))
  (check (number? 0.0))
  (check (number? 1.0))
  (check (number? 100.0))
  (check (complex? 1+2i))
  (check (complex? 1-2i))
  (check (complex? -1+2i))
  (check (complex? -1-2i))
  (check (not (real? 1+2i)))
  (check (not (real? 1-2i)))
  (check (not (real? -1+2i)))
  (check (not (real? -1-2i))))


