(use-package! "unit-test")

(define-test canonicalize-filename
  (check (runtime-error? (canonicalize-filename :foo)))
  (check (runtime-error? (canonicalize-filename 23)))
  
  (check (equal? (canonicalize-filename "") ""))
  (check (equal? (canonicalize-filename " ") ""))
  (check (equal? (canonicalize-filename "foo") "foo"))
  (check (equal? (canonicalize-filename " foo") "foo"))
  (check (equal? (canonicalize-filename "foo/") "foo/"))
  (check (equal? (canonicalize-filename "foo /") "foo /"))
  (check (equal? (canonicalize-filename "/foo") "/foo"))
  (check (equal? (canonicalize-filename "/foo/") "/foo/"))
  (check (equal? (canonicalize-filename "foo/bar") "foo/bar"))
  (check (equal? (canonicalize-filename "foo/bar/") "foo/bar/"))
  (check (equal? (canonicalize-filename "/foo/bar") "/foo/bar"))
  (check (equal? (canonicalize-filename "/foo/bar/") "/foo/bar/"))
  (check (equal? (canonicalize-filename "/foo/ bar/") "/foo/ bar/"))
  (check (equal? (canonicalize-filename "foo/bar/baz/xyzzy/fubar/snafu/") "foo/bar/baz/xyzzy/fubar/snafu/"))
  (check (equal? (canonicalize-filename "/foo/bar/baz/xyzzy/fubar/snafu/") "/foo/bar/baz/xyzzy/fubar/snafu/"))
  (check (equal? (canonicalize-filename "../bar/") "../bar/"))
  (check (equal? (canonicalize-filename "./bar/") "bar/"))
  (check (equal? (canonicalize-filename "foo/../bar/") "bar/"))
  (check (equal? (canonicalize-filename "foo/./bar/") "foo/bar/"))
  (check (equal? (canonicalize-filename "../") "../"))
  (check (equal? (canonicalize-filename "..//") "../"))
  (check (equal? (canonicalize-filename ".././") "../"))
  (check (equal? (canonicalize-filename "/") "/"))
  (check (equal? (canonicalize-filename "//") "/"))
  (check (equal? (canonicalize-filename "/./") "/"))
  (check (equal? (canonicalize-filename "**//") "**/"))
  (check (equal? (canonicalize-filename "**/./") "**/"))
  (check (equal? (canonicalize-filename "**/../") "**/../"))
  (check (equal? (canonicalize-filename "/**/") "/**/"))
  (check (equal? (canonicalize-filename "/**//") "/**/"))
  (check (equal? (canonicalize-filename "////") "/"))
  (check (equal? (canonicalize-filename "/**") "/**/*"))
  (check (equal? (canonicalize-filename "//**") "/**/*"))
  (check (runtime-error? (canonicalize-filename "/../"))))
