(use-package! "unit-test")

(define-test fast-io-lists-and-vectors
  (check (can-fast-io-round-trip? '()))
  (check (can-fast-io-round-trip? '(1)))
  (check (can-fast-io-round-trip? '(1 2)))
  (check (can-fast-io-round-trip? '(1 . 2)))
  (check (can-fast-io-round-trip? '(1 2 3)))
  (check (can-fast-io-round-trip? '(1 2 3 4 5 6 7 8 9 10)))
  (check (can-fast-io-round-trip? (make-list 260 #f)))

  (check (can-fast-io-round-trip? []))
  (check (can-fast-io-round-trip? [1]))
  (check (can-fast-io-round-trip? [1 2]))
  (check (can-fast-io-round-trip? [1 2 3]))
  (check (can-fast-io-round-trip? [1 2 3 4 5 6 7 8 9 10]))
  (check (can-fast-io-round-trip? (make-vector 260 #f)))

  (check (can-fast-io-round-trip? '(())))
  (check (can-fast-io-round-trip? '((1))))
  (check (can-fast-io-round-trip? '((1 2))))
  (check (can-fast-io-round-trip? '((1 . 2))))
  (check (can-fast-io-round-trip? '((1 2 3))))
  (check (can-fast-io-round-trip? '((1 2 3 4 5 6 7 8 9 10))))
  (check (can-fast-io-round-trip? (cons (make-list 260 #f))))

  (check (can-fast-io-round-trip? [[]]))
  (check (can-fast-io-round-trip? [[1]]))
  (check (can-fast-io-round-trip? [[1 2]]))
  (check (can-fast-io-round-trip? [[1 2 3]]))
  (check (can-fast-io-round-trip? [[1 2 3 4 5 6 7 8 9 10]]))
  (check (can-fast-io-round-trip? (vector (make-vector 260 #f))))

  (check (can-fast-io-round-trip? '([])))
  (check (can-fast-io-round-trip? '([1])))
  (check (can-fast-io-round-trip? '([1 2])))
  (check (can-fast-io-round-trip? '([1 2 3])))
  (check (can-fast-io-round-trip? '([1 2 3 4 5 6 7 8 9 10])))
  (check (can-fast-io-round-trip? (list (make-vector 260 #f))))

  (check (can-fast-io-round-trip? (vector '())))
  (check (can-fast-io-round-trip? (vector '(1))))
  (check (can-fast-io-round-trip? (vector '(1 2))))
  (check (can-fast-io-round-trip? (vector '(1 . 2))))
  (check (can-fast-io-round-trip? (vector '(1 2 3))))
  (check (can-fast-io-round-trip? (vector '(1 2 3 4 5 6 7 8 9 10))))

  (check (can-fast-io-round-trip? [[1] [2 3] [4 5 6] [7 8 9 10] [11 12 13 14 15]]))
  (check (can-fast-io-round-trip? '((1) (2 3) (4 5 6) (7 8 9 10) (11 12 13 14 15)))))
