(use-package! "unit-test")

(define-test parse-glob-pattern
  (test-case (equal? (scheme::parse-glob-pattern "foo") '("foo")))
  (test-case (equal? (scheme::parse-glob-pattern "*") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "**") '(:any-n)))

  (test-case (equal? (scheme::parse-glob-pattern "***") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "**?") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "*?*") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "*??") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "?**") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "?*?") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "??*") '(:any-n)))

  (test-case (equal? (scheme::parse-glob-pattern "????*") '(:any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "foo????*") '("foo" :any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "foo????*bar") '("foo" :any-n "bar")))
  (test-case (equal? (scheme::parse-glob-pattern "foo*?*?*?bar") '("foo" :any-n "bar")))

  (test-case (equal? (scheme::parse-glob-pattern "*.*") '(:any-n "." :any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "*.txt") '(:any-n ".txt")))
  (test-case (equal? (scheme::parse-glob-pattern "tests.*") '("tests." :any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "?") '(:any-1)))
  (test-case (equal? (scheme::parse-glob-pattern "??") '(:any-1 :any-1)))
  (test-case (equal? (scheme::parse-glob-pattern "???") '(:any-1 :any-1 :any-1)))
  (test-case (equal? (scheme::parse-glob-pattern "foo*") '("foo" :any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "*foo") '(:any-n "foo")))
  (test-case (equal? (scheme::parse-glob-pattern "foo?") '("foo" :any-1)))
  (test-case (equal? (scheme::parse-glob-pattern "?foo") '(:any-1 "foo")))
  (test-case (equal? (scheme::parse-glob-pattern "foo*foo") '("foo" :any-n "foo")))
  (test-case (equal? (scheme::parse-glob-pattern "foo?foo") '("foo" :any-1 "foo")))
  (test-case (equal? (scheme::parse-glob-pattern "*foo?foo*") '(:any-n "foo" :any-1 "foo" :any-n)))
  (test-case (equal? (scheme::parse-glob-pattern "?bar*baz") '(:any-1 "bar" :any-n "baz")))
  )
