(use-package! "unit-test")

(define-test string->number
  (check (runtime-error? (string->number 123 12)))
  (check (runtime-error? (string->number "123" 1)))
  (check (runtime-error? (string->number "123" -1)))
  (check (runtime-error? (string->number "123" 37)))
  (check (runtime-error? (string->number "123" 3.7)))
  (check (runtime-error? (string->number "123" :keyword)))
    
  (check (equal? #f (string->number "")))
  (check (equal? #f (string->number "" 2)))
  (check (equal? #f (string->number "" 8)))
  (check (equal? #f (string->number "" 10)))
  (check (equal? #f (string->number "" 16)))

  (check (equal? 0 (string->number "0")))
  (check (equal? 0 (string->number "-0")))
  (check (equal? 12 (string->number "12")))
  (check (equal? -12 (string->number "-12")))

  (check (equal? -1.2 (string->number "-1.2")))  

  (check (equal? 0 (string->number "0" 10)))
  (check (equal? 0 (string->number "-0" 10)))
  (check (equal? 12 (string->number "12" 10)))
  (check (equal? -12 (string->number "-12" 10)))
  (check (equal? #f (string->number "12f" 10)))
  (check (equal? #f (string->number "-12f" 10)))
  (check (equal? #f (string->number "-12g" 10)))
  (check (equal? #f (string->number "12-2" 10)))
  (check (equal? #f (string->number "12+2" 10)))
  (check (equal? #f (string->number "12i" 10)))
  
  (check (equal? 0 (string->number "0" 16)))
  (check (equal? 0 (string->number "-0" 16)))
  (check (equal? 18 (string->number "12" 16)))
  (check (equal? #f (string->number "1.2" 16)))
  (check (equal? -18 (string->number "-12" 16)))
  (check (equal? 51966 (string->number "cafe" 16)))
  (check (equal? -51966 (string->number "-cafe" 16)))
  (check (equal? 51966 (string->number "CAFE" 16)))
  (check (equal? #f (string->number "CA.FE" 16)))
  (check (equal? -51966 (string->number "-CAFE" 16)))

  (check (equal? 0 (string->number "0" 8)))
  (check (equal? 0 (string->number "-0" 8)))
  (check (equal? 10 (string->number "12" 8)))
  (check (equal? -10 (string->number "-12" 8)))
  (check (equal? #f (string->number "8" 8)))
  (check (equal? #f (string->number "9" 8)))
  (check (equal? #f (string->number "18" 8)))
  (check (equal? #f (string->number "19" 8)))
  (check (equal? #f (string->number "12f" 8)))
  (check (equal? #f (string->number "-12f" 8)))
  (check (equal? #f (string->number "-12g" 8)))
  (check (equal? #f (string->number "12-2" 8)))
  (check (equal? #f (string->number "12+2" 8)))
  (check (equal? #f (string->number "12i" 8)))

  (check (equal? 0 (string->number "0" 2)))
  (check (equal? 0 (string->number "-0" 2)))
  (check (equal? 12 (string->number "1100" 2)))
  (check (equal? -12 (string->number "-1100" 2)))

  (check (equal? #f (string->number "8" 2)))
  (check (equal? #f (string->number "9" 2)))
  (check (equal? #f (string->number "18" 2)))
  (check (equal? #f (string->number "19" 2)))
  (check (equal? #f (string->number "12f" 2)))
  (check (equal? #f (string->number "-12f" 2)))
  (check (equal? #f (string->number "-12g" 2)))
  (check (equal? #f (string->number "12-2" 2)))
  (check (equal? #f (string->number "12+2" 2)))
  (check (equal? #f (string->number "12i" 2))))
