(use-package! "unit-test")

(define-test equal?-atom
  (test-case (equal? 1 1))
  (test-case (equal? 1.0 1.0))
  (test-case (equal? #\a #\a))
  (test-case (equal? "" ""))
  (test-case (equal? "hello" "hello"))
  (test-case (equal? 'a 'a))
  (test-case (equal? :key1 :key1))
  (test-case (equal? #t #t))
  (test-case (equal? #f #f))
  (test-case (equal? () ()))
  (test-case (not (equal? 1 2)))
  (test-case (not (equal? 1.0 1.2)))
  (test-case (not (equal? #\a #\b)))
  (test-case (not (equal? "" "foo")))
  (test-case (not (equal? "foo" "")))
  (test-case (not (equal? "hello" "world")))
  (test-case (not (equal? 'a 'b)))
  (test-case (not (equal? :key1 :key3)))
  (test-case (not (equal? #f #t)))
  (test-case (not (equal? () 12)))
  )
