#!/bin/sh 


SCC0_BASE=`dirname $0`

# Fixup the SCANPATH to point to the build hierarchies scheme directory. This
# catches a some of the packages that are 'required' by s-core before the 
# scansh0 command line parser loads them.
SCANPATH=${SCC0_BASE}/../scheme:${SCANPATH}

gdb --args ${SCC0_BASE}/../scansh0 ${SCC0_BASE}/s-core.scf \
                           ${SCC0_BASE}/fasl-compiler.scf \
                           ${SCC0_BASE}/fasl-compiler-run.scf \
                           ${SCC0_BASE}/fasl-compiler0.scf \
                           $@
